sudo: required
services:
  - docker

before_install:
  - docker build -t dimohg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dimohg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-185630661221"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
